language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t manafov0817/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manafov0817/docker-react npm run test