language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t manafov0817/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manafov0817/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "MyDockerReact"
  env: "Mydockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-248104625541"
  bucket_path: "MyDockerReact"
  on:
    branch: main
  access_key_id: $aws-access-key
  secret_access_key: $aws-access-key